import { ContentItem, Fields } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class Event extends ContentItem {

    public title: Fields.TextField;
    public description: Fields.RichTextField;
    public taxonomy: Fields.TaxonomyField;
    public eventImage: Fields.AssetsField;
    public startDate: Fields.DateTimeField;
    public endDate: Fields.DateTimeField;
    public venue: Fields.TextField;
    public city: Fields.TextField;
    public country: Fields.TextField;
    
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'event_image') {
                    return 'eventImage';
                }

                if (fieldName === 'start_date') {
                    return 'startDate';
                }

                if (fieldName === 'end_date') {
                    return 'endDate';
                }

                return fieldName;
            })
        });    
    }
    
}