import { ContentItem, Fields } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class HeroUnit extends ContentItem {

    public title: Fields.TextField;
    public teaserImage: Fields.AssetsField;
    public marketingMessage: Fields.RichTextField;
    public ctaButtonLabel: Fields.TextField;
    
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'teaser_image') {
                    return 'teaserImage';
                }

                if (fieldName === 'marketing_message') {
                    return 'marketingMessage';
                }

                if (fieldName === 'cta_button_label') {
                    return 'ctaButtonLabel';
                }

                return fieldName;
            })
        });
    }
    
}