import { ContentItem, Fields } from 'kentico-cloud-delivery-typescript-sdk';
import { HeroUnit } from './heroUnit';
import { Feature } from './feature';
import { Testimonial } from './testimonial';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class Home extends ContentItem {

    public heroUnit: HeroUnit[];
    public businessOverview: Fields.RichTextField;
    public features: Feature[];
    public testimonial: Testimonial[];
    public metaKeywords: Fields.TextField;
    public metaDescription: Fields.TextField;
    
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'hero_unit') {
                    return 'heroUnit';
                }

                if (fieldName === 'business_overview') {
                    return 'businessOverview';
                }

                if (fieldName === 'meta_keywords') {
                    return 'metaKeywords';
                }

                if (fieldName === 'meta_description') {
                    return 'metaDescription';
                }

                return fieldName;
            })
        });
    }
    
}